/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bank.service.base;

import com.bank.model.customerRel;

import com.bank.service.customerRelLocalService;
import com.bank.service.customerRelService;
import com.bank.service.persistence.customerRelPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the customer rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.bank.service.impl.customerRelLocalServiceImpl}.
 * </p>
 *
 * @author priyanka
 * @see com.bank.service.impl.customerRelLocalServiceImpl
 * @see com.bank.service.customerRelLocalServiceUtil
 * @generated
 */
public abstract class customerRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements customerRelLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.bank.service.customerRelLocalServiceUtil} to access the customer rel local service.
	 */

	/**
	 * Adds the customer rel to the database. Also notifies the appropriate model listeners.
	 *
	 * @param customerRel the customer rel
	 * @return the customer rel that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public customerRel addcustomerRel(customerRel customerRel)
		throws SystemException {
		customerRel.setNew(true);

		return customerRelPersistence.update(customerRel, false);
	}

	/**
	 * Creates a new customer rel with the primary key. Does not add the customer rel to the database.
	 *
	 * @param uId the primary key for the new customer rel
	 * @return the new customer rel
	 */
	public customerRel createcustomerRel(long uId) {
		return customerRelPersistence.create(uId);
	}

	/**
	 * Deletes the customer rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param uId the primary key of the customer rel
	 * @return the customer rel that was removed
	 * @throws PortalException if a customer rel with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public customerRel deletecustomerRel(long uId)
		throws PortalException, SystemException {
		return customerRelPersistence.remove(uId);
	}

	/**
	 * Deletes the customer rel from the database. Also notifies the appropriate model listeners.
	 *
	 * @param customerRel the customer rel
	 * @return the customer rel that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public customerRel deletecustomerRel(customerRel customerRel)
		throws SystemException {
		return customerRelPersistence.remove(customerRel);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(customerRel.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return customerRelPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return customerRelPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return customerRelPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return customerRelPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public customerRel fetchcustomerRel(long uId) throws SystemException {
		return customerRelPersistence.fetchByPrimaryKey(uId);
	}

	/**
	 * Returns the customer rel with the primary key.
	 *
	 * @param uId the primary key of the customer rel
	 * @return the customer rel
	 * @throws PortalException if a customer rel with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public customerRel getcustomerRel(long uId)
		throws PortalException, SystemException {
		return customerRelPersistence.findByPrimaryKey(uId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return customerRelPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the customer rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of customer rels
	 * @param end the upper bound of the range of customer rels (not inclusive)
	 * @return the range of customer rels
	 * @throws SystemException if a system exception occurred
	 */
	public List<customerRel> getcustomerRels(int start, int end)
		throws SystemException {
		return customerRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of customer rels.
	 *
	 * @return the number of customer rels
	 * @throws SystemException if a system exception occurred
	 */
	public int getcustomerRelsCount() throws SystemException {
		return customerRelPersistence.countAll();
	}

	/**
	 * Updates the customer rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param customerRel the customer rel
	 * @return the customer rel that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public customerRel updatecustomerRel(customerRel customerRel)
		throws SystemException {
		return updatecustomerRel(customerRel, true);
	}

	/**
	 * Updates the customer rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param customerRel the customer rel
	 * @param merge whether to merge the customer rel with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the customer rel that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public customerRel updatecustomerRel(customerRel customerRel, boolean merge)
		throws SystemException {
		customerRel.setNew(false);

		return customerRelPersistence.update(customerRel, merge);
	}

	/**
	 * Returns the customer rel local service.
	 *
	 * @return the customer rel local service
	 */
	public customerRelLocalService getcustomerRelLocalService() {
		return customerRelLocalService;
	}

	/**
	 * Sets the customer rel local service.
	 *
	 * @param customerRelLocalService the customer rel local service
	 */
	public void setcustomerRelLocalService(
		customerRelLocalService customerRelLocalService) {
		this.customerRelLocalService = customerRelLocalService;
	}

	/**
	 * Returns the customer rel remote service.
	 *
	 * @return the customer rel remote service
	 */
	public customerRelService getcustomerRelService() {
		return customerRelService;
	}

	/**
	 * Sets the customer rel remote service.
	 *
	 * @param customerRelService the customer rel remote service
	 */
	public void setcustomerRelService(customerRelService customerRelService) {
		this.customerRelService = customerRelService;
	}

	/**
	 * Returns the customer rel persistence.
	 *
	 * @return the customer rel persistence
	 */
	public customerRelPersistence getcustomerRelPersistence() {
		return customerRelPersistence;
	}

	/**
	 * Sets the customer rel persistence.
	 *
	 * @param customerRelPersistence the customer rel persistence
	 */
	public void setcustomerRelPersistence(
		customerRelPersistence customerRelPersistence) {
		this.customerRelPersistence = customerRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.bank.model.customerRel",
			customerRelLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.bank.model.customerRel");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return customerRel.class;
	}

	protected String getModelClassName() {
		return customerRel.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = customerRelPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = customerRelLocalService.class)
	protected customerRelLocalService customerRelLocalService;
	@BeanReference(type = customerRelService.class)
	protected customerRelService customerRelService;
	@BeanReference(type = customerRelPersistence.class)
	protected customerRelPersistence customerRelPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private customerRelLocalServiceClpInvoker _clpInvoker = new customerRelLocalServiceClpInvoker();
}