/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bank.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the customerRel service. Represents a row in the &quot;bankcapital_customerRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bank.model.impl.customerRelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bank.model.impl.customerRelImpl}.
 * </p>
 *
 * @author priyanka
 * @see customerRel
 * @see com.bank.model.impl.customerRelImpl
 * @see com.bank.model.impl.customerRelModelImpl
 * @generated
 */
public interface customerRelModel extends BaseModel<customerRel> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer rel model instance should use the {@link customerRel} interface instead.
	 */

	/**
	 * Returns the primary key of this customer rel.
	 *
	 * @return the primary key of this customer rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this customer rel.
	 *
	 * @param primaryKey the primary key of this customer rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the u ID of this customer rel.
	 *
	 * @return the u ID of this customer rel
	 */
	public long getUId();

	/**
	 * Sets the u ID of this customer rel.
	 *
	 * @param uId the u ID of this customer rel
	 */
	public void setUId(long uId);

	/**
	 * Returns the customer ID of this customer rel.
	 *
	 * @return the customer ID of this customer rel
	 */
	@AutoEscape
	public String getCustomerId();

	/**
	 * Sets the customer ID of this customer rel.
	 *
	 * @param customerId the customer ID of this customer rel
	 */
	public void setCustomerId(String customerId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(customerRel customerRel);

	public int hashCode();

	public CacheModel<customerRel> toCacheModel();

	public customerRel toEscapedModel();

	public String toString();

	public String toXmlString();
}